In [17]:
import pandas as pd

In [18]:
dataset = pd.read_csv("Social_Network_Ads.csv")
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [19]:
dataset = dataset.drop("User ID",axis=1)
dataset = pd.get_dummies(dataset,drop_first=True)
dataset

     Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [20]:
dataset.shape

(400, 4)

In [21]:
dataset.describe()

              Age  EstimatedSalary   Purchased  Gender_Male
count  400.000000       400.000000  400.000000   400.000000
mean    37.655000     69742.500000    0.357500     0.490000
std     10.482877     34096.960282    0.479864     0.500526
min     18.000000     15000.000000    0.000000     0.000000
25%     29.750000     43000.000000    0.000000     0.000000
50%     37.000000     70000.000000    0.000000     0.000000
75%     46.000000     88000.000000    1.000000     1.000000
max     60.000000    150000.000000    1.000000     1.000000

In [22]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
Age                400 non-null int64
EstimatedSalary    400 non-null int64
Purchased          400 non-null int64
Gender_Male        400 non-null uint8
dtypes: int64(3), uint8(1)
memory usage: 9.9 KB

In [23]:
dataset.dtypes

Age                int64
EstimatedSalary    int64
Purchased          int64
Gender_Male        uint8
dtype: object

In [24]:
dataset.columns

Index(['Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [25]:
indep = dataset[['Age', 'EstimatedSalary', 'Gender_Male']]
dep = dataset[['Purchased']]

In [26]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(indep,dep,test_size=0.30,random_state=0)

In [27]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train,y_train)
y_predict = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_predict)
from sklearn.metrics import classification_report
cl = classification_report(y_test,y_predict)
print(cm)
print(cl)

[[74  5]
 [ 8 33]]
              precision    recall  f1-score   support

           0       0.90      0.94      0.92        79
           1       0.87      0.80      0.84        41

    accuracy                           0.89       120
   macro avg       0.89      0.87      0.88       120
weighted avg       0.89      0.89      0.89       120

C:\Users\HP\anaconda3\envs\aiml\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [28]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train,y_train)
y_predict = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_predict)
from sklearn.metrics import classification_report
cl = classification_report(y_test,y_predict)
print(cm)
print(cl)

[[68 11]
 [28 13]]
              precision    recall  f1-score   support

           0       0.71      0.86      0.78        79
           1       0.54      0.32      0.40        41

    accuracy                           0.68       120
   macro avg       0.62      0.59      0.59       120
weighted avg       0.65      0.68      0.65       120

C:\Users\HP\anaconda3\envs\aiml\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [30]:
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier.fit(X_train,y_train)
y_predict = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_predict)
from sklearn.metrics import classification_report
cl = classification_report(y_test,y_predict)
print(cm)
print(cl)

[[79  0]
 [41  0]]
              precision    recall  f1-score   support

           0       0.66      1.00      0.79        79
           1       0.00      0.00      0.00        41

    accuracy                           0.66       120
   macro avg       0.33      0.50      0.40       120
weighted avg       0.43      0.66      0.52       120

C:\Users\HP\anaconda3\envs\aiml\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\HP\anaconda3\envs\aiml\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

In [35]:
from sklearn.naive_bayes import ComplementNB
classifier = ComplementNB()
classifier.fit(X_train,y_train)
y_predict = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_predict)
from sklearn.metrics import classification_report
cl = classification_report(y_test,y_predict)
print(cm)
print(cl)

[[42 37]
 [20 21]]
              precision    recall  f1-score   support

           0       0.68      0.53      0.60        79
           1       0.36      0.51      0.42        41

    accuracy                           0.53       120
   macro avg       0.52      0.52      0.51       120
weighted avg       0.57      0.52      0.54       120

C:\Users\HP\anaconda3\envs\aiml\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [36]:
from sklearn.naive_bayes import CategoricalNB
classifier = CategoricalNB()
classifier.fit(X_train,y_train)
y_predict = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_predict)
from sklearn.metrics import classification_report
cl = classification_report(y_test,y_predict)
print(cm)
print(cl)

ImportError: cannot import name 'CategoricalNB' from 'sklearn.naive_bayes' (C:\Users\HP\anaconda3\envs\aiml\lib\site-packages\sklearn\naive_bayes.py)